<?php

namespace BackendBundle\Repository;

/**
 * BewertungRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BewertungRepository extends \Doctrine\ORM\EntityRepository
{
}
