<?php

namespace BackendBundle\Repository;

/**
 * FitnessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FitnessRepository extends \Doctrine\ORM\EntityRepository
{
}
